# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-16 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessPoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaBandWidthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=50)),
                ('UsedData', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='Tac',
            field=models.CharField(max_length=20),
        ),
    ]
